# Database Configuration
db.url=jdbc:mysql://localhost:3306/appointment_db
db.username=root
db.password=Kulkarni@2006

# Application Settings
app.slot.duration.minutes=60
app.working.hours.start=09
app.working.hours.end=18

# Email (SMTP) Configuration
mail.smtp.host=smtp.gmail.com
mail.smtp.port=587
mail.smtp.auth=true
mail.smtp.starttls=true
mail.sender.email=hrushikeshkulkarni06@gmail.com
mail.sender.password=smqhoxpntgtscsev
